export const TEXTURE = {
  DUNGEON_TILES: 'tex-dungeon-tiles',
  TORCH: 'tex-torch',
  PROPS: 'tex-props',
  CHEST: 'tex-chest',
  STAIRS: 'tex-stairs',
  HUD_ICONS: 'tex-hud-icons',
  COIN_ANIM: 'tex-coin-anim',
  PARTICLE_SPARK: 'tex-particle-spark',
  PARTICLE_BLOOD: 'tex-particle-blood',
  PARTICLE_BONE: 'tex-particle-bone',
  PARTICLE_WOOD: 'tex-particle-wood',
  DEBRIS_WOOD: 'tex-debris-wood',
  WEAPON_SWORD: 'tex-weapon-sword',
  BOW: 'tex-weapon-bow',
  BOW_DRAWN: 'tex-weapon-bow-drawn',
  ARROW: 'tex-weapon-arrow',
  SLASH_FX: 'tex-slash-fx',
  SLASH_WHIRLWIND: 'tex-slash-whirlwind',
  VIGNETTE: 'tex-vignette',
  BOSS_DEMON: 'tex-boss-demon',
  SKULL: 'tex-skull',
  PROJECTILE_DEMON: 'tex-projectile-demon',
  RANGER_IDLE: 'tex-ranger-idle',
  RANGER_RUN: 'tex-ranger-run',
  WIZARD_IDLE: 'tex-wizard-idle',
  WIZARD_RUN: 'tex-wizard-run',
  STAFF: 'tex-weapon-staff',
  WEAPON_BOSS_ORC_AXE: 'tex-weapon-boss-orc-axe',
  PROJECTILE_ENERGY: 'tex-projectile-energy',
  TILES_BIOME: 'tex-tiles-biome',
  TREE_PINE: 'tex-tree-pine',
  TREE_OAK: 'tex-tree-oak',
  BONFIRE: 'tex-bonfire',
  PROP_ROCK: 'tex-prop-rock',
  PROP_ROCK_LARGE: 'tex-prop-rock-large',
  PROP_BUSH: 'tex-prop-bush',
  PROP_CRATE: 'tex-prop-crate',
  PROP_BARREL: 'tex-prop-barrel',
  PROP_REEDS: 'tex-prop-reeds',
  PROP_STATUE: 'tex-prop-statue',
  PROP_CABIN: 'tex-prop-cabin',
  PROP_FENCE: 'tex-prop-fence',
  PROP_WORKBENCH: 'tex-prop-workbench',
  PROP_PRISON_BARS: 'tex-prop-prison-bars',
  PROP_CHAINS: 'tex-prop-chains',
  PROP_BLOOD_SPILL: 'tex-prop-blood-spill',
  PROP_MINE_SHAFT: 'tex-prop-mine-shaft',
  PROP_MINECART: 'tex-prop-minecart',
  PROP_LUPINE: 'tex-prop-lupine',
  PROP_MUSHROOM_GIANT: 'tex-prop-mushroom-giant',
  PROP_ICE_CRYSTAL: 'tex-prop-ice-crystal',
  PROP_VOID_OBELISK: 'tex-prop-void-obelisk',
  PARTICLE_DUST: 'tex-particle-dust',
  PARTICLE_SMOKE: 'tex-particle-smoke', 
  PARTICLE_LEAF: 'tex-particle-leaf',
  SHADOW: 'tex-shadow',
  PROP_SPIKES: 'tex-prop-spikes',
  FOUNTAIN_BLUE: 'tex-fountain-blue',
  FOUNTAIN_RED: 'tex-fountain-red',
  GAME_EMBLEM: 'tex-game-emblem',
  CHEST_ANIM: 'tex-chest-anim',
  WATER_WAVES: 'tex-water-waves',
  BONFIRE_STAGE: 'tex-bonfire-stage',
  BOSS_ORC_IDLE: 'tex-boss-orc-idle',
  BOSS_ORC_RUN: 'tex-boss-orc-run',
  ORC_WARRIOR_IDLE: 'tex-orc-warrior-idle',
  ORC_WARRIOR_RUN: 'tex-orc-warrior-run',
  MASKED_ORC_IDLE: 'tex-masked-orc-idle',
  MASKED_ORC_RUN: 'tex-masked-orc-run',
  ITEMS_32ROGUES: 'tex-items-32rogues',
  UI_PANEL_NINE: 'tex-ui-panel-nine',
  UI_SLOT_FRAME: 'tex-ui-slot-frame',
  UI_HERO_PORTRAIT_KNIGHT: 'tex-ui-hero-knight',
  UI_HERO_PORTRAIT_RANGER: 'tex-ui-hero-ranger',
  UI_HERO_PORTRAIT_WIZARD: 'tex-ui-hero-wizard',
  UI_SKULL_ORNAMENT: 'tex-ui-skull-ornament',
  UI_HP_BAR_FRAME: 'tex-ui-hp-bar-frame',
  UI_BOSS_BAR_FRAME: 'tex-ui-boss-bar-frame',
  UI_EMBER_ICON: 'tex-ui-ember-icon',
} as const;

export const ANIM = {
  TORCH_FLICKER: 'anim-torch-flicker',
  COIN_SPIN: 'anim-coin-spin',
  BOSS_DEMON_IDLE: 'anim-boss-demon-idle',
  BOSS_DEMON_RUN: 'anim-boss-demon-run',
  BOSS_ORC_IDLE: 'anim-boss-orc-idle',
  BOSS_ORC_RUN: 'anim-boss-orc-run',
  ORC_WARRIOR_IDLE: 'anim-orc-warrior-idle',
  ORC_WARRIOR_RUN: 'anim-orc-warrior-run',
  MASKED_ORC_IDLE: 'anim-masked-orc-idle',
  MASKED_ORC_RUN: 'anim-masked-orc-run',
  RANGER_IDLE: 'anim-ranger-idle',
  RANGER_RUN: 'anim-ranger-run',
  WIZARD_IDLE: 'anim-wizard-idle',
  WIZARD_RUN: 'anim-wizard-run',
  BONFIRE_FLICKER: 'anim-bonfire-flicker',
  SPIKES_CYCLE: 'anim-spikes-cycle',
  FOUNTAIN_BLUE_FLOW: 'anim-fountain-blue-flow',
  FOUNTAIN_RED_FLOW: 'anim-fountain-red-flow',
  CHEST_OPENING: 'anim-chest-opening',
  WATER_WAVE_CYCLE: 'anim-water-wave-cycle',
  // These will be used later when we load vendor spritesheets
} as const;

export const FONT = {
  TITLE: '"Cinzel Decorative", serif',
  UI: '"Russo One", sans-serif',
} as const;

// per-slot tint applied to remote-controlled players so 2-4 knights on
// screen stay visually distinguishable; slot 0 (white) leaves the sprite
// unmodified.
export const PLAYER_TINTS = [0xffffff, 0x8fd0ff, 0x8fffb0, 0xffe08f] as const;
export const PLAYER_LABEL_COLORS = ['#f0e2b8', '#8fd0ff', '#8fffb0', '#ffe08f'] as const;

export const DEPTH = {
  FLOOR: 0,
  BLOOD_DECAL: 5,
  DUST: 25,
  DECOR: 15, // static decor outside the y-sorted world (menu torches)
  SHADOW: 95,
  YSORT_BASE: 100, // GameScene world objects: depth = YSORT_BASE + y, so front/back sorts by position
  OVERLAY: 1000,
  UI: 1001,
} as const;
